### ISSUE TITLE
Questions about must_be_train_templates

### ISSUE THREAD

**Issue by ktxlh** [inbaroren/scfg-sampling-for-comp-gen#1]
What are the `must_be_train_templates` for?
https://github.com/inbaroren/scfg-sampling-for-comp-gen/blob/801236690cbe4f0b238f8a995ac994defe50075f/scripts/create_splits.py#L25-L28

How did you get these templates? Why must they be trained?
What will happen if they are not in the train set?

**Comment by inbaroren** [comment]
Hey,
There are few templates that are very frequent hence must be in the
training pool (can't be in the evalution set). Their frequency is related
to the generation process, and can be changed.
If the training synthetic pool was small it wasn't a good setup to test the
paper's hypothesis. However, based on our results a 5K training set is
enough data as long as it includes many templates.

Hope that's helpful.
Inbar
